import './globals.css';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { ReactQueryProvider } from '@/providers/ReactQueryProvider';
import SessionProvider from '@/providers/SessionProvider';
// import { options as authOptions } from '@/api/auth/[...nextauth]/options';
import Navbar from './components/navbar/Navbar';

export const metadata: Metadata = {
  title: 'Control de Comandas',
  description: 'Generated by BAMBU',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // const session = await getServerSession(authOptions);
  return (
    <html lang='en'>
      <body className='block'>
        <Navbar />
        {/* <SessionProvider session={session}> */}
          <ReactQueryProvider>{children}</ReactQueryProvider>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
